global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  rolling_window: true
  unknown_cost_value: 205
  update_frequency: 1
  publish_frequency: 1
  static_map: false
  width: 20.0
  height: 20.0
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.2

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: sonar, type: "range_sensor_layer::RangeSensorLayer"}
  - {name: obstacle_layer,           type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,                 type: "costmap_2d::InflationLayer"}
