TebLocalPlannerROS:
  #max_vel_x: 0.6
  #max_vel_theta: 0.6
  #max_vel_x_backwards: 0.4
  max_vel_x: 1.0
  max_vel_theta: 0.6
  max_vel_x_backwards: 0.4
  wheelbase: 0.25
  cmd_angle_instead_rotvel: true
  footprint_model/type: polygon
  #footprint_model/vertices: [ [0.23, -0.165], [-0.23, -0.165], [-0.23, 0.165], [0.23, 0.165] ]
  footprint_model/vertices: [[-0.325,-0.10], [0.075, -0.10], [0.075, 0.10], [-0.325, 0.10]]
  #xy_goal_tolerance: 0.25
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.5
  min_turning_radius: 0.82

  #min_obstacle_dist: 0.2
  min_obstacle_dist: 0.35
  enable_homotopy_class_planning: false

  max_global_plan_lookahead_dist: 4.0
  #max_global_plan_lookahead_dist: 8.0
  feasibility_check_no_poses: 8

  weight_kinematics_forward_drive: 10.0
