/* Auto-generated by genmsg_cpp for file /home/pses/catkin_ws/src/rososc/touchosc_msgs/msg/Label.msg */
#ifndef TOUCHOSC_MSGS_MESSAGE_LABEL_H
#define TOUCHOSC_MSGS_MESSAGE_LABEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include <apollo_13/CommonProperties.h>

namespace touchosc_msgs
{
template <class ContainerAllocator>
struct Label_ {
  typedef Label_<ContainerAllocator> Type;

  Label_()
  : header()
  , common()
  , value()
  {
  }

  Label_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , common(_alloc)
  , value(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::touchosc_msgs::CommonProperties_<ContainerAllocator>  _common_type;
   ::touchosc_msgs::CommonProperties_<ContainerAllocator>  common;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  value;


  typedef boost::shared_ptr< ::touchosc_msgs::Label_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::touchosc_msgs::Label_<ContainerAllocator>  const> ConstPtr;
}; // struct Label
typedef  ::touchosc_msgs::Label_<std::allocator<void> > Label;

typedef boost::shared_ptr< ::touchosc_msgs::Label> LabelPtr;
typedef boost::shared_ptr< ::touchosc_msgs::Label const> LabelConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::touchosc_msgs::Label_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::touchosc_msgs::Label_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace touchosc_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::touchosc_msgs::Label_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::touchosc_msgs::Label_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::touchosc_msgs::Label_<ContainerAllocator> > {
  static const char* value()
  {
    return "b5cfc77fbfd3429b0db9743556374f86";
  }

  static const char* value(const  ::touchosc_msgs::Label_<ContainerAllocator> &) { return value(); }
  static const uint64_t static_value1 = 0xb5cfc77fbfd3429bULL;
  static const uint64_t static_value2 = 0x0db9743556374f86ULL;
};

template<class ContainerAllocator>
struct DataType< ::touchosc_msgs::Label_<ContainerAllocator> > {
  static const char* value()
  {
    return "touchosc_msgs/Label";
  }

  static const char* value(const  ::touchosc_msgs::Label_<ContainerAllocator> &) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::touchosc_msgs::Label_<ContainerAllocator> > {
  static const char* value()
  {
    return "# TouchOSC Label Control\n\
\n\
Header header\n\
CommonProperties common\n\
string value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: touchosc_msgs/CommonProperties\n\
# Common functionality to all TouchOSC controls\n\
\n\
string tabpage          # Control tabpage\n\
string name             # Control Name\n\
int16 x                 # X position of the control\n\
int16 y                 # Y position of the control\n\
uint16 width            # Width of the control\n\
uint16 height           # Height of the control\n\
string visible          # Visibility of the control\n\
\n\
# Possible colors are:\n\
# \"red\", \"green\", \"blue\", \"yellow\", \"orange\", \"purple\", \"gray\"\n\
string color            # Color of the control\n\
\n\
";
  }

  static const char* value(const  ::touchosc_msgs::Label_<ContainerAllocator> &) { return value(); }
};

template<class ContainerAllocator> struct HasHeader< ::touchosc_msgs::Label_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::touchosc_msgs::Label_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::touchosc_msgs::Label_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.common);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Label_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::touchosc_msgs::Label_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::touchosc_msgs::Label_<ContainerAllocator> & v)
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "common: ";
s << std::endl;
    Printer< ::touchosc_msgs::CommonProperties_<ContainerAllocator> >::stream(s, indent + "  ", v.common);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TOUCHOSC_MSGS_MESSAGE_LABEL_H
