/* Auto-generated by genmsg_cpp for file /home/pses/catkin_ws/src/rososc/touchosc_msgs/msg/Tabpage.msg */
#ifndef TOUCHOSC_MSGS_MESSAGE_TABPAGE_H
#define TOUCHOSC_MSGS_MESSAGE_TABPAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace touchosc_msgs
{
template <class ContainerAllocator>
struct Tabpage_ {
  typedef Tabpage_<ContainerAllocator> Type;

  Tabpage_()
  : header()
  , tabpage()
  {
  }

  Tabpage_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , tabpage(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tabpage_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  tabpage;


  typedef boost::shared_ptr< ::touchosc_msgs::Tabpage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::touchosc_msgs::Tabpage_<ContainerAllocator>  const> ConstPtr;
}; // struct Tabpage
typedef  ::touchosc_msgs::Tabpage_<std::allocator<void> > Tabpage;

typedef boost::shared_ptr< ::touchosc_msgs::Tabpage> TabpagePtr;
typedef boost::shared_ptr< ::touchosc_msgs::Tabpage const> TabpageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::touchosc_msgs::Tabpage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::touchosc_msgs::Tabpage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace touchosc_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::touchosc_msgs::Tabpage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::touchosc_msgs::Tabpage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::touchosc_msgs::Tabpage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4213ffb5a43e14111c66fe04a2d8f4ec";
  }

  static const char* value(const  ::touchosc_msgs::Tabpage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4213ffb5a43e1411ULL;
  static const uint64_t static_value2 = 0x1c66fe04a2d8f4ecULL;
};

template<class ContainerAllocator>
struct DataType< ::touchosc_msgs::Tabpage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "touchosc_msgs/Tabpage";
  }

  static const char* value(const  ::touchosc_msgs::Tabpage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::touchosc_msgs::Tabpage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Used for tabpage switching\n\
\n\
Header header\n\
string tabpage\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::touchosc_msgs::Tabpage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::touchosc_msgs::Tabpage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::touchosc_msgs::Tabpage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::touchosc_msgs::Tabpage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.tabpage);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Tabpage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::touchosc_msgs::Tabpage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::touchosc_msgs::Tabpage_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tabpage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tabpage);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TOUCHOSC_MSGS_MESSAGE_TABPAGE_H

